# Generated by Django 2.2.9 on 2022-01-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20220102_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Добавьте комментарий к посту', verbose_name='Текст комментария'),
        ),
    ]
