# Generated by Django 2.2.16 on 2022-01-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_auto_20220130_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
