# Generated by Django 2.2.16 on 2022-02-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_auto_20220203_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile2',
        ),
    ]
