# Generated by Django 2.2.16 on 2022-02-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
